# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cb3c6cad74e820dc259c12fc1051c0f5937cc2818aa54c5e16e8a460784514c3487279edd0ca91b70ef24482e78725748140ab7b6ebbebd98f9eee15ed92bcf

test:
  secret_key_base: 980d018826ce53c51f51c0ebc2179773951fac7262ca70ac8a1b02706810a7c18af07014f80cee0bbd254140ed01df79cac083dbee675e3cc5657ec9a50a7273

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
